[app]
  #app 名称
  name = "PengZong的个人博客"
  slogan = "没有什么比做无用功更让人痛苦的事情了！"
  #app url
  url  = "http://localhost"
  addr = ":8181"
  #单元测试调试信息
  debug = false
  #网站备案号
  icp = "京ICP备15054073号"
  #github Webhooks中配置的 Secret
  secret = "goblog"
#资源文件配置
[res]
    root_dir = "resources"
    #文章目录
    docs_dir = "resources/docs"
    #文档目录
    books_dir = "resources/books"
